/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import java.awt.Component;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.net.URL;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.border.Border;
import javax.swing.text.html.StyleSheet;

/**
 *
 * @author sofia
 */
public class login extends javax.swing.JFrame {

     Color  btnColor= new Color(155,82,87);
     Color btnColorEntered = new Color(188,116,121);
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
    }
        public class fondo_degradado2 extends JPanel{
            
                   protected void paintComponent(Graphics g) {
                   super.paintComponent(g);
                   int width=getWidth();
                   int height=getHeight();

                    // Convertimos el objeto Graphics en un objeto Graphics2D
                   Graphics2D g2d = (Graphics2D) g;

                   // Define los colores del degradado
                   Color  colorFin= new Color(253,236,201);
                   Color colorInicio =new Color(250, 143, 177);

                   // Define los puntos de inicio y fin del degradado (x1, y1, x2, y2)
                   int x1 = 0;
                   int y1 = 0;
                   int x2 = width; // Ancho del componente
                   int y2 = height;

                    // Crea el objeto GradientPaint para el degradado lineal
                   GradientPaint gradient = new GradientPaint(0, 0, colorInicio, 180, height, colorFin);

                   // Establece el degradado como color de fondo
                   g2d.setPaint(gradient);

                   // Dibuja un rectángulo con el degradado como fondo  
                   g2d.fillRect(0, 0, width, height);
               }
        }
      
        
        
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo_degradado = fondo_degradado  = new fondo_degradado2();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fondo_blanco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnAcceder = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnVerPassword = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1011, 702));
        setMinimumSize(new java.awt.Dimension(1011, 702));
        setResizable(false);
        setSize(new java.awt.Dimension(1011, 702));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo_degradado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fondo_degradado.setMaximumSize(new java.awt.Dimension(491, 702));
        fondo_degradado.setMinimumSize(new java.awt.Dimension(491, 702));

        jLabel3.setFont(new java.awt.Font("Vladimir Script", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("D'Shopink Boutique");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html><p align=\"center\">¡Bienvenido! <br> a</p></html>\n");

        javax.swing.GroupLayout fondo_degradadoLayout = new javax.swing.GroupLayout(fondo_degradado);
        fondo_degradado.setLayout(fondo_degradadoLayout);
        fondo_degradadoLayout.setHorizontalGroup(
            fondo_degradadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondo_degradadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(fondo_degradadoLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addContainerGap())
        );
        fondo_degradadoLayout.setVerticalGroup(
            fondo_degradadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondo_degradadoLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        getContentPane().add(fondo_degradado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 491, 702));
        fondo_degradado= new fondo_degradado2();

        fondo_blanco.setBackground(new java.awt.Color(255, 255, 255));
        fondo_blanco.setForeground(new java.awt.Color(117, 177, 177));
        fondo_blanco.setMaximumSize(new java.awt.Dimension(1011, 702));
        fondo_blanco.setMinimumSize(new java.awt.Dimension(1011, 702));
        fondo_blanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(117, 117, 117));
        jLabel1.setText("<html> Comenzar nuevo <br> turno </html>");
        jLabel1.setToolTipText("");
        jLabel1.setAlignmentX(569.0F);
        jLabel1.setAlignmentY(252.0F);
        fondo_blanco.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 371, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(117, 117, 117));
        jLabel2.setText("Contraseña:");
        fondo_blanco.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 204, 30));

        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtUser.setForeground(new java.awt.Color(117, 117, 117));
        txtUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(117, 117, 117), 2, true));
        txtUser.setCaretColor(new java.awt.Color(102, 102, 102));
        txtUser.setSelectedTextColor(new java.awt.Color(117, 117, 117));
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        fondo_blanco.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 357, 72));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(117, 117, 117), 2, true));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        fondo_blanco.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 357, 72));

        btnAcceder.setBackground(new java.awt.Color(155, 82, 87));
        btnAcceder.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        btnAcceder.setForeground(new java.awt.Color(255, 255, 255));
        btnAcceder.setText("Acceder");
        btnAcceder.setBorderPainted(false);
        btnAcceder.setFocusPainted(false);
        btnAcceder.setFocusable(false);
        btnAcceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAccederMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAccederMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAccederMouseExited(evt);
            }
        });
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });
        fondo_blanco.add(btnAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 183, 56));

        btnSalir.setBackground(new java.awt.Color(155, 82, 87));
        btnSalir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setActionCommand("Salir");
        btnSalir.setBorderPainted(false);
        btnSalir.setFocusPainted(false);
        btnSalir.setFocusable(false);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        fondo_blanco.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 114, 56));

        btnVerPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVerPassword.setForeground(new java.awt.Color(153, 153, 153));
        btnVerPassword.setText("Ver");
        btnVerPassword.setBorderPainted(false);
        btnVerPassword.setContentAreaFilled(false);
        btnVerPassword.setFocusPainted(false);
        btnVerPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPasswordActionPerformed(evt);
            }
        });
        fondo_blanco.add(btnVerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 390, -1, 34));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(117, 117, 117));
        jLabel5.setText("Usuario:");
        fondo_blanco.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 204, -1));

        getContentPane().add(fondo_blanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1011, 702));

        setSize(new java.awt.Dimension(1025, 709));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccederActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnAccederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccederMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAccederMouseClicked

    private void btnAccederMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccederMouseEntered
        // TODO add your handling code here:
        btnAcceder.setBackground(btnColorEntered);
    }//GEN-LAST:event_btnAccederMouseEntered

    private void btnAccederMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccederMouseExited
        // TODO add your handling code heres:
        btnAcceder.setBackground(btnColor);
    }//GEN-LAST:event_btnAccederMouseExited

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        // TODO add your handling code here:
        btnAcceder.setBackground(btnColorEntered);
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        // TODO add your handling code here:
        
        btnAcceder.setBackground(btnColor);
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVerPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPasswordActionPerformed
        // TODO add your handling code here:
        JToggleButton btn = (JToggleButton) evt.getSource();
    if (btn.isSelected()) {
        txtPassword.setEchoChar((char) 0); // Muestra el texto real
    } else {
        txtPassword.setEchoChar('*'); // Oculta el texto de la contraseña con asteriscos
    }
    }//GEN-LAST:event_btnVerPasswordActionPerformed

                
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }
    

    
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnSalir;
    private javax.swing.JToggleButton btnVerPassword;
    private javax.swing.JPanel fondo_blanco;
    private javax.swing.JPanel fondo_degradado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}

