/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author sofia
 */
public class productos extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
        Color  btnColorEntered= new Color(152,82,87);
        Color btnColorExit = new Color(193,142,151);
    public productos() {
        this.setExtendedState(MAXIMIZED_BOTH);
        
        // Establece el comportamiento al cerrar la ventana
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        // Agrega un WindowListener para interceptar el evento de cierre
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                confirmarCierre();
            }
        });
        
        initComponents();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private void confirmarCierre() {   
                 cerrarPrograma a = new cerrarPrograma();
                 a.setVisible(true);
    }
     
    private void cambiarPanel() {
        jPanelNuevoProducto.setVisible(false);
        tablaProductos.setVisible(true);
        
        
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        panelBackground = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnDepartamento = new javax.swing.JButton();
        btnVentasPeriodo = new javax.swing.JButton();
        btnPromociones = new javax.swing.JButton();
        btnImportar = new javax.swing.JButton();
        btnCatalogo = new javax.swing.JButton();
        btnNuevoP = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnApartados = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnClientes1 = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnProductos1 = new javax.swing.JButton();
        btnCorte = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        panelProductos = new javax.swing.JPanel();
        jPanelNuevoProducto = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        btnNuevoP1 = new javax.swing.JButton();
        btnNuevoP2 = new javax.swing.JButton();
        btnNuevoP3 = new javax.swing.JButton();
        tablaProductos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelDepartamentos = new javax.swing.JPanel();
        tablaProductos1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));
        panelBackground.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(191, 130, 135));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IMAGEN");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 300, 60));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Punto de venta");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, 80));

        panelBackground.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30000, 80));

        jLabel7.setBackground(new java.awt.Color(89, 89, 89));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("       Productos");
        jLabel7.setOpaque(true);
        panelBackground.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1540, 30));

        jPanel4.setBackground(new java.awt.Color(214, 212, 212));

        btnDepartamento.setBackground(new java.awt.Color(89, 89, 89));
        btnDepartamento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnDepartamento.setForeground(new java.awt.Color(255, 255, 255));
        btnDepartamento.setText("Deportamento");
        btnDepartamento.setBorderPainted(false);
        btnDepartamento.setFocusPainted(false);
        btnDepartamento.setFocusable(false);
        btnDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDepartamentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDepartamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDepartamentoMouseExited(evt);
            }
        });
        btnDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartamentoActionPerformed(evt);
            }
        });

        btnVentasPeriodo.setBackground(new java.awt.Color(89, 89, 89));
        btnVentasPeriodo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnVentasPeriodo.setForeground(new java.awt.Color(255, 255, 255));
        btnVentasPeriodo.setText("Ventas por per.");
        btnVentasPeriodo.setBorderPainted(false);
        btnVentasPeriodo.setFocusPainted(false);
        btnVentasPeriodo.setFocusable(false);
        btnVentasPeriodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentasPeriodoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVentasPeriodoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVentasPeriodoMouseExited(evt);
            }
        });
        btnVentasPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasPeriodoActionPerformed(evt);
            }
        });

        btnPromociones.setBackground(new java.awt.Color(89, 89, 89));
        btnPromociones.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnPromociones.setForeground(new java.awt.Color(255, 255, 255));
        btnPromociones.setText("Promociones");
        btnPromociones.setBorderPainted(false);
        btnPromociones.setFocusPainted(false);
        btnPromociones.setFocusable(false);
        btnPromociones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPromocionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPromocionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPromocionesMouseExited(evt);
            }
        });
        btnPromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromocionesActionPerformed(evt);
            }
        });

        btnImportar.setBackground(new java.awt.Color(89, 89, 89));
        btnImportar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnImportar.setForeground(new java.awt.Color(255, 255, 255));
        btnImportar.setText("Importar");
        btnImportar.setBorderPainted(false);
        btnImportar.setFocusPainted(false);
        btnImportar.setFocusable(false);
        btnImportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImportarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnImportarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnImportarMouseExited(evt);
            }
        });
        btnImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarActionPerformed(evt);
            }
        });

        btnCatalogo.setBackground(new java.awt.Color(89, 89, 89));
        btnCatalogo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnCatalogo.setForeground(new java.awt.Color(255, 255, 255));
        btnCatalogo.setText("Catálogo");
        btnCatalogo.setBorderPainted(false);
        btnCatalogo.setFocusPainted(false);
        btnCatalogo.setFocusable(false);
        btnCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCatalogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCatalogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCatalogoMouseExited(evt);
            }
        });
        btnCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoActionPerformed(evt);
            }
        });

        btnNuevoP.setBackground(new java.awt.Color(89, 89, 89));
        btnNuevoP.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnNuevoP.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoP.setText("Producto");
        btnNuevoP.setBorderPainted(false);
        btnNuevoP.setFocusPainted(false);
        btnNuevoP.setFocusable(false);
        btnNuevoP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevoPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevoPMouseExited(evt);
            }
        });
        btnNuevoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnNuevoP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDepartamento)
                .addGap(4, 4, 4)
                .addComponent(btnVentasPeriodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPromociones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCatalogo)
                .addGap(117, 117, 117))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNuevoP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPromociones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVentasPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnImportar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        panelBackground.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 300000, 50));

        jPanel2.setBackground(new java.awt.Color(237, 191, 194));

        btnApartados.setBackground(new java.awt.Color(193, 142, 151));
        btnApartados.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnApartados.setForeground(new java.awt.Color(255, 255, 255));
        btnApartados.setText("Apartados");
        btnApartados.setBorderPainted(false);
        btnApartados.setFocusPainted(false);
        btnApartados.setFocusable(false);
        btnApartados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnApartadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnApartadosMouseExited(evt);
            }
        });
        btnApartados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApartadosActionPerformed(evt);
            }
        });

        btnVentas.setBackground(new java.awt.Color(193, 142, 151));
        btnVentas.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVentas.setText("Ventas");
        btnVentas.setBorderPainted(false);
        btnVentas.setFocusPainted(false);
        btnVentas.setFocusable(false);
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVentasMouseExited(evt);
            }
        });
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnClientes1.setBackground(new java.awt.Color(193, 142, 151));
        btnClientes1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnClientes1.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes1.setText("Clientes");
        btnClientes1.setBorderPainted(false);
        btnClientes1.setFocusPainted(false);
        btnClientes1.setFocusable(false);
        btnClientes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientes1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientes1MouseExited(evt);
            }
        });
        btnClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientes1ActionPerformed(evt);
            }
        });

        btnInventario.setBackground(new java.awt.Color(193, 142, 151));
        btnInventario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(255, 255, 255));
        btnInventario.setText("Inventario");
        btnInventario.setBorderPainted(false);
        btnInventario.setFocusPainted(false);
        btnInventario.setFocusable(false);
        btnInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInventarioMouseExited(evt);
            }
        });
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });

        btnProductos1.setBackground(new java.awt.Color(155, 82, 87));
        btnProductos1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnProductos1.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos1.setText("Productos");
        btnProductos1.setBorderPainted(false);
        btnProductos1.setFocusPainted(false);
        btnProductos1.setFocusable(false);

        btnCorte.setBackground(new java.awt.Color(193, 142, 151));
        btnCorte.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnCorte.setForeground(new java.awt.Color(255, 255, 255));
        btnCorte.setText("Corte");
        btnCorte.setBorderPainted(false);
        btnCorte.setFocusPainted(false);
        btnCorte.setFocusable(false);
        btnCorte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCorteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCorteMouseExited(evt);
            }
        });
        btnCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorteActionPerformed(evt);
            }
        });

        btnReporte.setBackground(new java.awt.Color(193, 142, 151));
        btnReporte.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte.setText("Reportes");
        btnReporte.setBorderPainted(false);
        btnReporte.setFocusPainted(false);
        btnReporte.setFocusable(false);
        btnReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteMouseExited(evt);
            }
        });
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApartados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProductos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCorte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReporte)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApartados, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelBackground.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 2000, 50));

        panelProductos.setBackground(new java.awt.Color(255, 255, 255));

        jPanelNuevoProducto.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNuevoProducto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Código de barras");
        jPanelNuevoProducto.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Descripción");
        jPanelNuevoProducto.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 109, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Precio Costo");
        jPanelNuevoProducto.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 109, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Ganancia");
        jPanelNuevoProducto.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 109, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Precio de venta");
        jPanelNuevoProducto.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 131, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Precio mayoreo");
        jPanelNuevoProducto.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Departamento");
        jPanelNuevoProducto.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 126, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("en este momento.");
        jPanelNuevoProducto.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 173, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Hay");
        jPanelNuevoProducto.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 35, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanelNuevoProducto.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 150, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanelNuevoProducto.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 350, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanelNuevoProducto.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 150, -1));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanelNuevoProducto.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 150, -1));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanelNuevoProducto.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 150, -1));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanelNuevoProducto.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 150, -1));

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanelNuevoProducto.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 71, -1));

        btnNuevoP1.setBackground(new java.awt.Color(255, 51, 51));
        btnNuevoP1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnNuevoP1.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoP1.setText("Eliminar");
        btnNuevoP1.setBorderPainted(false);
        btnNuevoP1.setFocusPainted(false);
        btnNuevoP1.setFocusable(false);
        btnNuevoP1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoP1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevoP1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevoP1MouseExited(evt);
            }
        });
        btnNuevoP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoP1ActionPerformed(evt);
            }
        });
        jPanelNuevoProducto.add(btnNuevoP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 40));

        btnNuevoP2.setBackground(new java.awt.Color(169, 206, 103));
        btnNuevoP2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnNuevoP2.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoP2.setText("Nuevo");
        btnNuevoP2.setBorderPainted(false);
        btnNuevoP2.setFocusPainted(false);
        btnNuevoP2.setFocusable(false);
        btnNuevoP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoP2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevoP2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevoP2MouseExited(evt);
            }
        });
        btnNuevoP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoP2ActionPerformed(evt);
            }
        });
        jPanelNuevoProducto.add(btnNuevoP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 40));

        btnNuevoP3.setBackground(new java.awt.Color(255, 204, 102));
        btnNuevoP3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnNuevoP3.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoP3.setText("Editar");
        btnNuevoP3.setBorderPainted(false);
        btnNuevoP3.setFocusPainted(false);
        btnNuevoP3.setFocusable(false);
        btnNuevoP3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoP3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevoP3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevoP3MouseExited(evt);
            }
        });
        btnNuevoP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoP3ActionPerformed(evt);
            }
        });
        jPanelNuevoProducto.add(btnNuevoP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 40));

        tablaProductos.setBackground(new java.awt.Color(246, 221, 223));
        tablaProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setText("PRODUCTOS");
        tablaProductos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 30, 131, -1));

        jTable1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo de barras", "Descripcion", "Precio costo", "Ganancia", "Precio de venta", "Precio mayoreo", "Departamento", "Cant. Inventario"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        tablaProductos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 900, -1));

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addComponent(jPanelNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 3000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(tablaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 3000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelBackground.add(panelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        panelDepartamentos.setBackground(new java.awt.Color(255, 255, 255));

        tablaProductos1.setBackground(new java.awt.Color(246, 221, 223));
        tablaProductos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(89, 89, 89));
        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(89, 89, 89));
        jLabel3.setText("Departamentos");
        tablaProductos1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 40));

        javax.swing.GroupLayout panelDepartamentosLayout = new javax.swing.GroupLayout(panelDepartamentos);
        panelDepartamentos.setLayout(panelDepartamentosLayout);
        panelDepartamentosLayout.setHorizontalGroup(
            panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaProductos1, javax.swing.GroupLayout.DEFAULT_SIZE, 3557, Short.MAX_VALUE)
        );
        panelDepartamentosLayout.setVerticalGroup(
            panelDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepartamentosLayout.createSequentialGroup()
                .addComponent(tablaProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, 3000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        panelBackground.add(panelDepartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        getContentPane().add(panelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 3000, 3000));

        setBounds(0, 0, 1510, 1261);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoPMouseClicked

    private void btnNuevoPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoPMouseEntered

    private void btnNuevoPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoPMouseExited

    private void btnNuevoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoPActionPerformed

    private void btnDepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepartamentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDepartamentoMouseClicked

    private void btnDepartamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepartamentoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDepartamentoMouseEntered

    private void btnDepartamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepartamentoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDepartamentoMouseExited

    private void btnDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDepartamentoActionPerformed

    private void btnVentasPeriodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasPeriodoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasPeriodoMouseClicked

    private void btnVentasPeriodoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasPeriodoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasPeriodoMouseEntered

    private void btnVentasPeriodoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasPeriodoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasPeriodoMouseExited

    private void btnVentasPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasPeriodoActionPerformed

    private void btnPromocionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPromocionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPromocionesMouseClicked

    private void btnPromocionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPromocionesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPromocionesMouseEntered

    private void btnPromocionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPromocionesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPromocionesMouseExited

    private void btnPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromocionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPromocionesActionPerformed

    private void btnImportarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImportarMouseClicked

    private void btnImportarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImportarMouseEntered

    private void btnImportarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImportarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImportarMouseExited

    private void btnImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImportarActionPerformed

    private void btnCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatalogoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatalogoMouseClicked

    private void btnCatalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatalogoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatalogoMouseEntered

    private void btnCatalogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatalogoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatalogoMouseExited

    private void btnCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatalogoActionPerformed

    private void btnApartadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApartadosMouseEntered
        // TODO add your handling code here:
        btnApartados.setBackground(btnColorEntered);
    }//GEN-LAST:event_btnApartadosMouseEntered

    private void btnApartadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApartadosMouseExited
        // TODO add your handling code heres:
        btnApartados.setBackground(btnColorExit);
    }//GEN-LAST:event_btnApartadosMouseExited

    private void btnApartadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApartadosActionPerformed
        // TODO add your handling code here:
        apartados a = new apartados();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnApartadosActionPerformed

    private void btnVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseEntered
        // TODO add your handling code here:
        btnVentas.setBackground(btnColorEntered);
    }//GEN-LAST:event_btnVentasMouseEntered

    private void btnVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseExited
        // TODO add your handling code here:
        btnVentas.setBackground(btnColorExit);
    }//GEN-LAST:event_btnVentasMouseExited

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        dashboard a = new dashboard();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnClientes1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientes1MouseEntered
        // TODO add your handling code here:
        btnClientes1.setBackground(btnColorEntered);
    }//GEN-LAST:event_btnClientes1MouseEntered

    private void btnClientes1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientes1MouseExited
        // TODO add your handling code here:
        btnClientes1.setBackground(btnColorExit);
    }//GEN-LAST:event_btnClientes1MouseExited

    private void btnClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientes1ActionPerformed
        // TODO add your handling code here:
        Clientes clientes = new Clientes();
        clientes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnClientes1ActionPerformed

    private void btnInventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseEntered
        // TODO add your handling code here:
        btnInventario.setBackground(btnColorEntered);
    }//GEN-LAST:event_btnInventarioMouseEntered

    private void btnInventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventarioMouseExited
        // TODO add your handling code here:
        btnInventario.setBackground(btnColorExit);
    }//GEN-LAST:event_btnInventarioMouseExited

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
        inventario inv = new inventario();
        inv.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnCorteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCorteMouseEntered
        // TODO add your handling code here:
        btnCorte.setBackground(btnColorEntered);
    }//GEN-LAST:event_btnCorteMouseEntered

    private void btnCorteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCorteMouseExited
        // TODO add your handling code here:
        btnCorte.setBackground(btnColorExit);
    }//GEN-LAST:event_btnCorteMouseExited

    private void btnCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorteActionPerformed
        // TODO add your handling code here:
        corte cort = new corte();
        cort.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCorteActionPerformed

    private void btnReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseEntered
        // TODO add your handling code here:
        btnReporte.setBackground(btnColorEntered);
    }//GEN-LAST:event_btnReporteMouseEntered

    private void btnReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseExited
        // TODO add your handling code here:
        btnReporte.setBackground(btnColorExit);
    }//GEN-LAST:event_btnReporteMouseExited

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        reportes rep = new reportes();
        rep.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReporteActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void btnNuevoP1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoP1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoP1MouseClicked

    private void btnNuevoP1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoP1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoP1MouseEntered

    private void btnNuevoP1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoP1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoP1MouseExited

    private void btnNuevoP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoP1ActionPerformed

    private void btnNuevoP2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoP2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoP2MouseClicked

    private void btnNuevoP2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoP2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoP2MouseEntered

    private void btnNuevoP2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoP2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoP2MouseExited

    private void btnNuevoP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoP2ActionPerformed

    private void btnNuevoP3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoP3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoP3MouseClicked

    private void btnNuevoP3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoP3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoP3MouseEntered

    private void btnNuevoP3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoP3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoP3MouseExited

    private void btnNuevoP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoP3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productos().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApartados;
    private javax.swing.JButton btnCatalogo;
    private javax.swing.JButton btnClientes1;
    private javax.swing.JButton btnCorte;
    private javax.swing.JButton btnDepartamento;
    private javax.swing.JButton btnImportar;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnNuevoP;
    private javax.swing.JButton btnNuevoP1;
    private javax.swing.JButton btnNuevoP2;
    private javax.swing.JButton btnNuevoP3;
    private javax.swing.JButton btnProductos1;
    private javax.swing.JButton btnPromociones;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton btnVentasPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelNuevoProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelDepartamentos;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel tablaProductos;
    private javax.swing.JPanel tablaProductos1;
    // End of variables declaration//GEN-END:variables
}
